### ISSUE TITLE
mapper_parsing_exception on a Symfony 5.3 + PHP 8.0 project

### ISSUE THREAD

**Issue by sergiosanchezalvarez** [PcComponentes/apm-symfony-http-kernel#11]
First of all, here is my configuration:

**Composer.json**

```json
"require": {
   "pccomponentes/apm-symfony-http-kernel": "^0.1.7",
   "zoilomora/elastic-apm-agent-php": "^1.0"
}
```

Then i have to set APM tracer instance

**services.yaml**
```yaml
    apm.configuration:
        class: \ZoiloMora\ElasticAPM\Configuration\CoreConfiguration
        arguments:
            -  { appName: 'Nidum APM Service' }

    apm.reporter:
        class: \ZoiloMora\ElasticAPM\Reporter\ApmServerCurlReporter
        arguments:
            - 'http://192.168.3.44:9200'

    apm.poolFactory:
        class: \ZoiloMora\ElasticAPM\Pool\Memory\MemoryPoolFactory
        calls:
            -   method: create

    apm.tracer:
        class: \ZoiloMora\ElasticAPM\ElasticApmTracer
        arguments:
            $coreConfiguration: '@apm.configuration'
            $reporter: '@apm.reporter'
            $poolFactory: '@apm.poolFactory'
```

Then, configure the HTTP Kernel APM

**services.yaml**
```yaml
    PcComponentes\ElasticAPM\Symfony\Component\HttpKernel\EventSubscriber:
        class: PcComponentes\ElasticAPM\Symfony\Component\HttpKernel\EventSubscriber
        autoconfigure: true
        arguments:
            $router: '@router'
            $elasticApmTracer: '@apm.tracer'
```

When I make any request to my app, the `ApmServerCurlReporter.php` is called and this is the response of curl call:

```json
{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"failed to parse"}],"type":"mapper_parsing_exception","reason":"failed to parse","caused_by":{"type":"illegal_argument_exception","reason":"Malformed content, found extra data after parsing: START_OBJECT"}},"status":400}
```

![image](https://user-images.githubusercontent.com/1696402/134335801-a18d0e61-8308-4a76-ac24-88a7fd49964e.png)
